### ISSUE TITLE
特权模式的标准中，部分表格显示不全

### ISSUE THREAD

**Issue by devindang** [ISRC-CAS/riscv-isa-manual-cn#1]
问题发生在仓库中编译好的 pdf 文件中，如图所示，
<img width="1060" alt="CleanShot 2023-08-22 at 23 08 35@2x" src="https://github.com/isrc-cas/riscv-isa-manual-cn/assets/39517801/83cf738d-6b31-439d-ba52-a49be3c296bc">
发现的页数为7，11

**Comment by sunshaoce** [comment]
![image](https://github.com/isrc-cas/riscv-isa-manual-cn/assets/57467643/a30105c7-ab79-449b-8a8b-c754ad888489)

原文就是这样，而且都是有规律的重复，我认为可以不展开。
